[tool.poetry]
name = "management"
version = "0.1.1"
description = ""
authors = ["Diabl <dath.vg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
toml = "0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
